CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL, 
    description TEXT,
    deliverydate DATE NOT NULL
)

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER
)

-- INSERT PROJECTS --
INSERT INTO projects(name, priority, description, deliverydate) 
    VALUES('Make a app', 1, 'Using Dart', '2019-12-31')

INSERT INTO projects(name, priority, description, deliverydate) 
    VALUES('Make a web', 1, 'Using React', '2020-15-01')

-- INSERT TASKS -- 
INSERT INTO tasks(name, done, projectId)
    VALUES('download dart', false, 1)

INSERT INTO tasks(name, done, projectId)
    VALUES('download react', false, 2)